config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"

  post "/" => "home#create", as: :sessions
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  def display_user_list
      "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
   render "index"
  end

  def new
    # by default it willrender new.htm.erb file
  end

  def create
    falg = true

    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
          render plain: "You have entered the correct password!"
     else
        render plain: "Incorrect password!"
     end


  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   skip_before_action :verify_authenticity_token
  def index
      render plain: User.all.map { |user| user.display_user_list}
  end





#   def create

#       first_name = params[:first_name]
#       last_name = params[:last_name]
#       email = params[:email]
#       password = params[:password]

#       new_user = User.create!(

#           first_name: first_name,
#           last_name: last_name,
#           email: email,
#           password: password,
#         )

#         render plain: "added new user!"
#     end

def create
   User.create!(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password]
      # password_digest: digest(params[:password])
    )
    redirect_to "/"
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class = "HomePageTitle"> Welcome to Delicous Catering! </h1>

<section class="UsersNew">
   <%= form_with url: sessions_path do |form| %>

         <div class="Form-section">
            <p class="FormInput-label"> Email </p>
              <%= form.email_field :email, class: "Form-input" %>
         </div>
         <div class="Form-section">
            <p class="FormInput-label"> Password </p>
            <%= form.password_field :password, class: "Form-input" %>
        </div>

        <div class="Form-section">
           <%= form.submit "Login!", class: "Form-submit" %>
        </div>
    <% end %>

</section>

<p class= "NewUsers"> Don't have an account yet? <%= link_to "sign up here", new_user_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h2> Create Account</h2>

<section class="UsersNew">
   <%= form_with url: users_path do |form| %>
         <div class="Form-section">
            <p class="FormInput-label"> First name: </p>
             <%= form.text_field :first_name, class: "Form-input" %>
         </div>
         <div class="Form-section">
             <p class="FormInput-label"> Last name: </p>
             <%= form.text_field :last_name, class: "Form-input" %>
         </div>
         <div class="Form-section">
            <p class="FormInput-label"> Email </p>
              <%= form.email_field :email, class: "Form-input" %>
         </div>
         <div class="Form-section">
            <p class="FormInput-label"> Password </p>
            <%= form.password_field :password, class: "Form-input" %>
        </div>

        <div class="Form-section">
           <%= form.submit "sign-up!", class: "Form-submit" %>
        </div>
    <% end %>

</section>